-- ダミーデータ挿入
insert into sponsors (name, logo_url, website_url, type, description) values
  -- メインスポンサー
  ('メインスポンサー株式会社', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'main', 'ここに会社の説明文が入ります。'),

  -- ゴールドスポンサー 1～5
  ('ゴールドスポンサー 1', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'gold', null),
  ('ゴールドスポンサー 2', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'gold', null),
  ('ゴールドスポンサー 3', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'gold', null),
  ('ゴールドスポンサー 4', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'gold', null),
  ('ゴールドスポンサー 5', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'gold', null),

  -- シルバースポンサー 1～30
  ('シルバースポンサー 1', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 2', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 3', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 4', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 5', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 6', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 7', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 8', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 9', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 10', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 11', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 12', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 13', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 14', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 15', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 16', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 17', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 18', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 19', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 20', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 21', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 22', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 23', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 24', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 25', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 26', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 27', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 28', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 29', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),
  ('シルバースポンサー 30', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'silver', null),

  -- サポータースポンサー 1～50
  ('サポータースポンサー 1', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 2', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 3', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 4', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 5', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 6', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 7', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 8', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 9', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 10', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 11', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 12', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 13', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 14', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 15', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 16', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 17', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 18', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 19', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 20', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 21', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 22', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 23', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 24', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 25', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 26', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 27', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 28', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 29', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 30', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 31', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 32', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 33', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 34', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 35', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 36', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 37', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 38', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 39', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 40', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 41', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 42', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 43', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 44', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 45', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 46', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 47', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 48', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 49', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null),
  ('サポータースポンサー 50', 'https://npxqbgysjxykcykaiutm.supabase.co/storage/v1/object/sign/img/main%20sponsor.png', 'https://luminostudio.net/', 'supporter', null)
;
